/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ikz;

import Anggota.DaftarAnggota;
import Buku.DaftarBuku;
import Buku.KembalikanBuku;
import Buku.PerpanjangBuku;
import Buku.PinjamBuku;

/**
 *
 * @author Deva Wibowoo
 */
public class MenuAdminMDI extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdminMDI
     */
    public MenuAdminMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        mnBuku = new javax.swing.JMenu();
        mnDaftarBuku = new javax.swing.JMenuItem();
        mnPinjam = new javax.swing.JMenuItem();
        mnKembali = new javax.swing.JMenuItem();
        mnPerpanjang = new javax.swing.JMenuItem();
        mnAnggota = new javax.swing.JMenu();
        mnDaftarAnggota = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogout);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        mnBuku.setText("Buku");

        mnDaftarBuku.setText("Daftar Buku");
        mnDaftarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDaftarBukuActionPerformed(evt);
            }
        });
        mnBuku.add(mnDaftarBuku);

        mnPinjam.setText("Pinjam Buku");
        mnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPinjamActionPerformed(evt);
            }
        });
        mnBuku.add(mnPinjam);

        mnKembali.setText("Kembalikan Buku");
        mnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKembaliActionPerformed(evt);
            }
        });
        mnBuku.add(mnKembali);

        mnPerpanjang.setText("Perpanjang");
        mnPerpanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPerpanjangActionPerformed(evt);
            }
        });
        mnBuku.add(mnPerpanjang);

        jMenuBar1.add(mnBuku);

        mnAnggota.setText("Anggota");

        mnDaftarAnggota.setText("Daftar Anggota");
        mnDaftarAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDaftarAnggotaActionPerformed(evt);
            }
        });
        mnAnggota.add(mnDaftarAnggota);

        jMenuBar1.add(mnAnggota);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        Login l = new Login();
        l.show();
        this.dispose();
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnDaftarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDaftarBukuActionPerformed
        DaftarBuku db = new DaftarBuku();
        Desktop.add(db);
        db.setVisible(true);
    }//GEN-LAST:event_mnDaftarBukuActionPerformed

    private void mnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPinjamActionPerformed
        PinjamBuku pb = new PinjamBuku();
        Desktop.add(pb);
        pb.setVisible(true);
    }//GEN-LAST:event_mnPinjamActionPerformed

    private void mnDaftarAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDaftarAnggotaActionPerformed
        DaftarAnggota da = new DaftarAnggota();
        Desktop.add(da);
        da.setVisible(true);
    }//GEN-LAST:event_mnDaftarAnggotaActionPerformed

    private void mnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKembaliActionPerformed
        KembalikanBuku kb = new KembalikanBuku();
        Desktop.add(kb);
        kb.setVisible(true);
    }//GEN-LAST:event_mnKembaliActionPerformed

    private void mnPerpanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPerpanjangActionPerformed
        PerpanjangBuku pb = new PerpanjangBuku();
        Desktop.add(pb);
        pb.setVisible(true);
    }//GEN-LAST:event_mnPerpanjangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnAnggota;
    private javax.swing.JMenu mnBuku;
    private javax.swing.JMenuItem mnDaftarAnggota;
    private javax.swing.JMenuItem mnDaftarBuku;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnKembali;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnPerpanjang;
    private javax.swing.JMenuItem mnPinjam;
    // End of variables declaration//GEN-END:variables
}
